version: '3.8'
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run e8422924-f71f-428c-a144-7fdc2ca71413
    env_file:
      - .env
    restart: always
    networks:
      - cloudflared_internet
      - cloudflared_portainer
      - cloudflared_frontend
      - cloudflared_moodle
      - cloudflared_adminer

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    networks:
      - cloudflared_portainer

  frontend-webapp:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend-webapp
    networks:
      - cloudflared_frontend
      - webapp

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=postgres
    networks:
      - webapp

  adminer:
    image: adminer
    restart: always
    networks:
      - cloudflared_adminer

  mariadb:
    image: docker.io/bitnami/mariadb:11.4
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_ALLOW_EMPTY_PASSWORD=${MARIADB_ALLOW_EMPTY_PASSWORD}
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      - moodle

  moodle:
    image: docker.io/bitnami/moodle:4.5
    environment:
      - MOODLE_DATABASE_HOST=${MOODLE_DATABASE_HOST}
      - MOODLE_DATABASE_PORT_NUMBER=${MOODLE_DATABASE_PORT_NUMBER}
      - MOODLE_DATABASE_USER=${MOODLE_DATABASE_USER}
      - MOODLE_DATABASE_NAME=${MOODLE_DATABASE_NAME}
      - MOODLE_DATABASE_PASSWORD=${MOODLE_DATABASE_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
      - MOODLE_USERNAME=${MOODLE_USERNAME}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
    networks:
      - cloudflared_moodle
      - moodle

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
  portainer_data:
    driver: local

networks:
  cloudflared_internet:
    driver: bridge
  cloudflared_portainer:
    internal: true
  cloudflared_frontend:
    internal: true
  cloudflared_moodle:
    internal: true
  cloudflared_adminer:
    internal: true
  webapp:
    internal: true
  moodle:
    internal: true