FROM node:lts-alpine3.19 AS builder
RUN apk add --no-cache git
RUN mkdir -p /home/luiszamorano
RUN git clone https://github.com/espaciodtcmas/frontend-webapp.git /home/luiszamorano
WORKDIR /home/luiszamorano
RUN npm install
RUN npm run build
CMD tail -f /dev/null

FROM nginx:alpine
COPY --from=builder /home/luiszamorano/dist/ /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
